name: Node CI environment

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        working-directory: ./application
        run: npm i --ignore-scripts

      - name: Run ESLint
        with:
          eslint-config-path: "./application/.eslintrc.yml"
          custom-directory: "./application"
          repo-token: ${{secrets.GITHUB_TOKEN}}
        run: node_modules/.bin/eslint src/
